version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    covax: 
        build: .
        environment: 
            - PORT=3000
    mongo:
        image: mongo
        environment: 
            MONGO_INITDB_ROOT_USERNAME: abhinav
            MONGO_INITDB_ROOT_PASSWORD: Supru@0111
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db: