version: "3"
services:
    covax: 
        build: 
            context: .
            args:
                NODE_ENV: production
        deploy:
            replicas: 4
            restart_policy: 
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            update_config:
                parallelism: 2
                delay: 15s
                failure_action: rollback 
        environment: 
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
        labels:
            - "com.centurylinklabs.watchtower.scope=covax"
            - "traefik.http.routers.speedtest.rule=Host(`covax.abhijh.xyz`)"
            - "traefik.http.routers.speedtest.tls=true"
            - "traefik.http.routers.speedtest.tls.certresolver=leresolver"
            - "traefik.enable=true"      
    mongo:
        environment: 
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}