version: "3"
services:
    nginx:
        ports:
            - "3000:80"
        labels:
            - "traefik.http.routers.covax.rule=Host(`covax.abhijh.xyz`)"
            - "traefik.http.routers.covax.tls=true"
            - "traefik.http.routers.covax.tls.certresolver=leresolver"
            - "traefik.http.routers.covax.middlewares=traefik-forward-auth"
            - "traefik.enable=true"
    covax:
        dns: 1.1.1.1
        build: 
            context: .
            args:
                NODE_ENV: production
        deploy:
            replicas: 1
            restart_policy: 
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            update_config:
                parallelism: 1
                delay: 15s
                failure_action: rollback 
        environment: 
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}    
    mongo:
        environment: 
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}