version: "3"
services:
    covax: 
        build: 
            context: .
            args:
                NODE_ENV: production
        deploy:
            replicas: 4
            restart_policy: any
            update_config:
                parallelism: 2
                delay: 15s
                failure_action: rollback 
        environment: 
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
        labels:
            - "com.centurylinklabs.watchtower.scope=covax"
    mongo:
        environment: 
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    watchtower:
        image: containrrr/watchtower 
        dns:
            - 1.1.1.1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment: 
            - WATCHTOWER_TRACE=true
            - WATCHTOWER_DEBUG=true
            - WATCHTOWER_POLL_INTERVAL=60
        command: --scope covax
        labels:
            - "com.centurylinklabs.watchtower.scope=covax"