version: "3"
services: 
    nginx:
        ports:
            - "3000:80"
    covax: 
        build: 
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_USER=abhinav
            - MONGO_PASSWORD=Supru@0111
            - EMAIL_USERNAME=${EMAIL_USERNAME}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}    
        command: npm run dev
    mongo:
        environment: 
            MONGO_INITDB_ROOT_USERNAME: abhinav
            MONGO_INITDB_ROOT_PASSWORD: Supru@0111